// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAdminRole = "admin_role"

// AdminRole 运营管理后台角色定义表
type AdminRole struct {
	RoleID       uint32  `gorm:"column:role_id;type:int unsigned;primaryKey;autoIncrement:true;comment:角色ID" json:"role_id"`                                                                     // 角色ID
	RoleNameZhCN string  `gorm:"column:role_name_zh_CN;type:varchar(64);not null;uniqueIndex:uni_group_name,priority:2;index:idx_role_name_cn,priority:1;comment:角色中文名称" json:"role_name_zh_CN"` // 角色中文名称
	RoleNameEn   *string `gorm:"column:role_name_en;type:varchar(64);index:idx_role_name_en,priority:1;comment:角色英文名称" json:"role_name_en"`                                                      // 角色英文名称
	RoleGroupID  uint32  `gorm:"column:role_group_id;type:int unsigned;not null;uniqueIndex:uni_group_name,priority:1;comment:角色分组 ID" json:"role_group_id"`                                     // 角色分组 ID
	GroupNameCn  string  `gorm:"column:group_name_cn;type:varchar(32);not null;index:fk_group_name_cn,priority:1;comment:角色分组中文名（冗余）" json:"group_name_cn"`                                      // 角色分组中文名（冗余）
	GroupNameEn  *string `gorm:"column:group_name_en;type:varchar(32);index:fk_group_name_en,priority:1;comment:角色分组英文名（冗余）" json:"group_name_en"`                                               // 角色分组英文名（冗余）
	RoleGrade    *int16  `gorm:"column:role_grade;type:tinyint;comment:权限等级，等级越大，权限越小（暂未启用，待定）" json:"role_grade"`                                                                               // 权限等级，等级越大，权限越小（暂未启用，待定）
	Privileges   *string `gorm:"column:privileges;type:varchar(1024);comment:权限列表，逗号分隔" json:"privileges"`                                                                                       // 权限列表，逗号分隔
	Ranking      *int32  `gorm:"column:ranking;type:int;default:1;comment:排序位置" json:"ranking"`                                                                                                  // 排序位置
	InitState    *int16  `gorm:"column:init_state;type:tinyint;default:2;comment:初始化状态：1-系统初始化角色;2-非系统初始化角色" json:"init_state"`                                                                  // 初始化状态：1-系统初始化角色;2-非系统初始化角色
	Remarks      *string `gorm:"column:remarks;type:varchar(1024);comment:备注" json:"remarks"`                                                                                                    // 备注
	CreateTime   *int32  `gorm:"column:create_time;type:int" json:"create_time"`
	ModifyTime   *int32  `gorm:"column:modify_time;type:int" json:"modify_time"`
	IsSystem     *int16  `gorm:"column:is_system;type:tinyint;default:2;comment:是否为系统管理员：2-否；1-是" json:"is_system"` // 是否为系统管理员：2-否；1-是
	Status       *int16  `gorm:"column:status;type:tinyint;default:1;comment:状态：0-删除；1-有效" json:"status"`           // 状态：0-删除；1-有效
}

// TableName AdminRole's table name
func (*AdminRole) TableName() string {
	return TableNameAdminRole
}
