// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAdminAccount = "admin_account"

// AdminAccount 运营管理后台登录账号信息表
type AdminAccount struct {
	AccountID     uint32     `gorm:"column:account_id;type:int unsigned;primaryKey;autoIncrement:true" json:"account_id" avatar:"account_id"`
	AccountName   string     `gorm:"column:account_name;type:char(16);not null;index:idx_account_name,priority:1;comment:登录用户名" json:"account_name" avatar:"account_name"` // 登录用户名
	PwdExpirein   *uint32    `gorm:"column:pwd_expirein;type:int unsigned;comment:密码过期时间" json:"pwd_expirein" avatar:"pwd_expirein"`                                       // 密码过期时间
	RoleID        *uint32    `gorm:"column:role_id;type:int unsigned;index:idx_role_id,priority:1;comment:角色ID" json:"role_id" avatar:"role_id"`                           // 角色ID
	RoleNameCn    *string    `gorm:"column:role_name_cn;type:varchar(64);index:fk_role_name_cn,priority:1;comment:角色中文名称" json:"role_name_cn" avatar:"role_name_cn"`       // 角色中文名称
	RoleNameEn    *string    `gorm:"column:role_name_en;type:varchar(64);index:idx_role_name_en,priority:1;comment:角色英文名称" json:"role_name_en" avatar:"role_name_en"`      // 角色英文名称
	GroupID       *uint32    `gorm:"column:group_id;type:int unsigned;comment:分组ID" json:"group_id" avatar:"group_id"`                                                     // 分组ID
	GroupName     *string    `gorm:"column:group_name;type:varchar(16);comment:分组名称" json:"group_name" avatar:"group_name"`                                                // 分组名称
	RealName      string     `gorm:"column:real_name;type:varchar(16);not null;comment:真实姓名" json:"real_name" avatar:"real_name"`                                          // 真实姓名
	Avatar        *string    `gorm:"column:avatar;type:char(40);comment:头像文件名" json:"avatar" avatar:"avatar"`                                                              // 头像文件名
	Mobile        string     `gorm:"column:mobile;type:varchar(11);not null" json:"id,string,omitempty" avatar:"mobile" json2:"id,string,omitempty"`
	EmailYyp      *string    `gorm:"column:email;type:varchar(32)" json:"email" avatar:"email"` // 这个是自定义的email注释信息
	Remarks       *string    `gorm:"column:remarks;type:varchar(1024)" json:"remarks" avatar:"remarks"`
	BindIP        *string    `gorm:"column:bind_ip;type:varchar(1024);comment:绑定IP地址" json:"bind_ip" avatar:"bind_ip"`                                                // 绑定IP地址
	BindMac       *string    `gorm:"column:bind_mac;type:char(32);comment:绑定Mac地址" json:"bind_mac" avatar:"bind_mac"`                                                 // 绑定Mac地址
	OperatorID    *uint32    `gorm:"column:operator_id;type:int unsigned;comment:最后修改人ID" json:"operator_id" avatar:"operator_id"`                                    // 最后修改人ID
	OperatorName  *string    `gorm:"column:operator_name;type:varchar(16);comment:最后修改人姓名" json:"operator_name" avatar:"operator_name"`                               // 最后修改人姓名
	ModifyTime    *uint32    `gorm:"column:modify_time;type:int unsigned;comment:最后修改时间" json:"modify_time" avatar:"modify_time"`                                     // 最后修改时间
	CreateTime    *uint32    `gorm:"column:create_time;type:int unsigned;comment:创建时间" json:"create_time" avatar:"create_time"`                                       // 创建时间
	LastLoginTime *uint32    `gorm:"column:last_login_time;type:int unsigned;comment:最后登录时间" json:"last_login_time" avatar:"last_login_time"`                         // 最后登录时间
	LastLoginIP   *string    `gorm:"column:last_login_ip;type:char(16);comment:最后登录IP" json:"last_login_ip" avatar:"last_login_ip"`                                   // 最后登录IP
	LastLoginMac  *string    `gorm:"column:last_login_mac;type:char(32);comment:最后登录电脑MAC地址" json:"last_login_mac" avatar:"last_login_mac"`                           // 最后登录电脑MAC地址
	InitState     *uint16    `gorm:"column:init_state;type:tinyint unsigned;default:2;comment:初始状态：1-系统初始用户；2-非系统初始用户" json:"init_state" avatar:"init_state"`         // 初始状态：1-系统初始用户；2-非系统初始用户
	IsSystemAdmin *uint16    `gorm:"column:is_system_admin;type:tinyint unsigned;default:2;comment:是否为系统管理员：1-是；2-否" json:"is_system_admin" avatar:"is_system_admin"` // 是否为系统管理员：1-是；2-否
	Status        *uint16    `gorm:"column:status;type:tinyint unsigned;default:1;comment:状态：0-删除；1-正常；2-锁定" json:"status" avatar:"status"`                           // 状态：0-删除；1-正常；2-锁定
	name          *string    `gorm:"gormName" json:"name"`
	Roles         *AdminRole `gorm:"foreignKey:RoleID;references:RoleID" json:"roles,string,omitempty" json_x_tag:"abcdef"`
}

// TableName AdminAccount's table name
func (*AdminAccount) TableName() string {
	return TableNameAdminAccount
}
